### ISSUE TITLE
ReferenceError when using POST Commands

### ISSUE THREAD

**Issue by bhdschmidt** [4ley/nodejs-bitcoin-de-api#10]
Hello 4ley,

I really appreaciate your node js bitcoin de wrapper library. I was very successful using it with get commands, but I receive one error when I use a post command like this one:

bitcoinde.post('orders', {max_amount: '0.0081' ,min_amount: '0.006', price: '10000.0' , trading_pair: 'btceur', type: 'sell'})
	.then((result) => {
       console.log(result);
	})
	.catch((error) => {
		console.error(error);
});

The error is a Reference Error: queryParams is not defined. Can you give me any advice?

Regards,
Bernhard

**Comment by 4ley** [comment]
Thanks for fixing, your request was merged.
