### ISSUE TITLE
Switch from callbacks to Promises

### ISSUE THREAD

**Issue by neuhaus** [4ley/nodejs-bitcoin-de-api#3]
What do you think about changing the module to use Promises instead of callbacks?

I made the necessary changes (parts of them are untested) over in my fork at
https://github.com/neuhaus/nodejs-bitcoin-de-api

**Comment by 4ley** [comment]
That's definitely a good idea. I will add support as soon as possible.

**Comment by neuhaus** [comment]
now that you merged the v2 PR I can try to create a PR for this..

**Comment by neuhaus** [comment]
please have a look at pull request #5
