### ISSUE TITLE
bug in sorting of query string

### ISSUE THREAD

**Issue by neuhaus** [4ley/nodejs-bitcoin-de-api#4]
When trying sorting the query string, a new object is created and passed to querystring's stringify method.

In the querystring module, `Object.keys()` is used to iterate through the array.

The order of the keys [is not determined](https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties) according to the specification, so the sorting is useless. It could break at any given moment.

Possible solution: use the module `query-string` instead of `querystring`, it sorts the keys during `stringify`.

I have implemented this in my fork in [this commit](https://github.com/neuhaus/nodejs-bitcoin-de-api/commit/e91ab6d68b77cb5470bfd392f56d37f7952c5c17)

**Comment by 4ley** [comment]
I will check on this. Thanks!

**Comment by neuhaus** [comment]
This issue is also fixed in pull request #5
