### ISSUE TITLE
get 'trades' returns undefined

### ISSUE THREAD

**Issue by masterkain** [4ley/nodejs-bitcoin-de-api#8]
hello, has anyone been able to fetch private trade history from bitcoin.de?

```
bitcoinde.get('trades', null)
    .then((result) => {
        console.log(result.data);
    })
    .catch((error) => {
        console.error(error);
    });
```

returns `undefined` in console

**Comment by 4ley** [comment]
Hi, please try` console.log(result.trades);`. They key for trades is `trades`
